app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app, Flask
from flask_login import login_user, login_required, current_user, logout_user
from flask_wtf.csrf import CSRFProtect
from werkzeug.security import generate_password_hash, check_password_hash
from app import db, limiter
from app.models import User, Asset, Customer, Manufacturer
from app.forms import RegistrationForm, LoginForm, AssetForm, CustomerForm, ManufacturerForm
import logging

main = Blueprint('main', __name__)


app = Flask(__name__)
csrf = CSRFProtect(app)

logging.basicConfig(filename='app.log', level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler())


@main.errorhandler(429)
def ratelimit_handler(e):
    form = LoginForm()
    flash("Too many requests, you have been locked out for one minute.", 'danger')
    return render_template('login.html', form=form), 429

# Lines 29 to 36 ensure that the index.html page is loaded when accessing the root URL, which occurs when the app starts running on the server


@main.route('/')
def index():
    current_app.config.update(
        SESSION_COOKIE_SECURE=True,
        SESSION_COOKIE_HTTPONLY=True,
        SESSION_COOKIE_SAMESITE='Strict'
    )
    return render_template('index.html')


# Lines 42 to 74 ensure that when the register.html page is accessed, the registration form is retrieved. When the user submits the form, validation takes place to query the User class and check the database to make sure a user cannot register with a username that has already been used, and if that username does already exist then a warning message will display to ask the user to choose a different one. It will also check to make sure that the user doesn't use the same information in the username and password fields, if they do then a warning message will display saying that the data in these fields must be different. Another check follows to ensure that the data entered into the password and confirm password fields is the same, if it doesn't then the user will be informed that the information must match. Following this, the password chosen is hashed using the Werkzeug library's scrypt method to encrypt the password within the database so that it is not stored in plain text. Then, the user is automatically set as a regular user so that they can perform CRU (Create, Read, Update) operations, but not CRUD (Create, Read, Update, Delete) operations, which are reserved for admin users. The new user's data is committed to the database, and they are redirected to the login page where a flash message informs them that registration was successful


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(
            username=form.username.data).first()
        if existing_user:
            flash(
                'Username is already taken. Please choose a different username.', 'danger')
            logging.warning(
                'Attempted to register with existing username: %s', form.username.data)
        elif form.username.data == form.password.data:
            flash('Username and password must be different.', 'danger')
        elif form.password.data != form.confirm_password.data:
            flash('Password and confirm password must match.', 'danger')
        else:
            hashed_password = generate_password_hash(
                form.password.data, method='scrypt')
            new_user = User(username=form.username.data,
                            password=hashed_password, role='regular')
            db.session.add(new_user)
            db.session.commit()
            flash('Registration successful. Please log in below', 'success')
            logging.info('User registered successfully: %s',
                         form.username.data)
            return redirect(url_for('main.login'))

    for _, errors in form.errors.items():
        for error in errors:
            flash(error, 'danger')
            logging.error(error)

    return render_template('register.html', form=form)


# Lines 80 to 99 ensure that when the register.html page is accessed, the login form is retrieved. When the user attempts to login with their details, validation takes place to check that the username and hashed password match an entry in the user table within the database. If an incorrect username or password is entered amd submitted, they will be unable to login and will see a flash message informing them that their details are incorrect. If the username and password are correct and a match, the user is redirected to the homepage and informed of their successful login


@main.route('/login', methods=['GET', 'POST'])
@limiter.limit("5/minute", key_func=lambda: request.remote_addr)
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            flash('Successfully logged in', 'success')
            logging.info('User logged in successfully: %s', form.username.data)
            return redirect(url_for('main.index'))
        else:
            flash('Invalid username or password', 'danger')
            logging.warning(
                'Invalid login attempt with username: %s', form.username.data)
    for _, errors in form.errors.items():
        for error in errors:
            flash(error, 'danger')
            logging.error(error)
    return render_template('login.html', form=form)


# Lines 105 to 112 ensure that the user is redirected to logout.html when they click on the logout button, upon which they will encounter a dialog box asking if they want to confirm or cancel the logout action. If they confirm the action, the user will be logged out of the application and redirected to the homepage, upon which they will see a flashed message informing them of their successful logout


@main.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    if request.method == 'POST':
        logout_user()
        flash('Successfully logged out', 'success')
        return redirect(url_for('main.index'))
    return render_template('logout.html')


# Lines 118 to 137 ensure that when the assets.html page is accessed, the assets form is retrieved. Validation takes place on submission to check that the data in each field matches the database model, and if it does, the new record is committed to the database and a flashed message appears to inform the user of the successful submission


@main.route('/assets', methods=['GET', 'POST'])
@login_required
def assets():
    form = AssetForm()

    form.manufacturer.choices = [(m.id, m.name)
                                 for m in Manufacturer.query.all()]
    form.customer.choices = [(c.id, c.name) for c in Customer.query.all()]

    if form.validate_on_submit():
        new_asset = Asset(category=form.category.data, comments=form.comments.data, user_id=current_user.id,
                          manufacturer_id=form.manufacturer.data, customer_id=form.customer.data)
        db.session.add(new_asset)
        db.session.commit()
        flash('Asset created', 'success')
        logging.info('New asset created by user: %s', current_user.username)
        return redirect(url_for('main.assets'))

    assets = Asset.query.all()
    return render_template('assets.html', form=form, assets=assets)


# The asset edit route (lines 143 to 175) directs the user to the edit_asset.html page and prepopulates the fields with the data that forms the selected record retrieved from the database. Validation again takes place upon submission, and the user is redirected back to the assets page and informed of the successful edited submission


@main.route('/assets/<int:asset_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_asset(asset_id):
    asset = Asset.query.get_or_404(asset_id)

    form = AssetForm()

    form.customer.choices = [(customer.id, customer.name)
                             for customer in Customer.query.all()]
    form.manufacturer.choices = [(manufacturer.id, manufacturer.name)
                                 for manufacturer in Manufacturer.query.all()]

    if request.method == 'POST':
        if form.validate_on_submit():
            asset.category = form.category.data
            asset.comments = form.comments.data
            asset.customer_id = form.customer.data
            asset.manufacturer_id = form.manufacturer.data
            db.session.commit()
            flash('Asset updated', 'success')
            logging.info('Asset updated by user: %s', current_user.username)
            return redirect(url_for('main.assets'))
        else:
            flash('Form validation failed', 'danger')
            logging.error(
                'Form validation failed for asset edit by user: %s', current_user.username)
    else:
        form.category.data = asset.category
        form.comments.data = asset.comments
        form.customer.data = asset.customer_id
        form.manufacturer.data = asset.manufacturer_id

    return render_template('edit_asset.html', form=form, asset=asset)


# If the user logged in is marked as an admin within the database, the asset delete route (lines 181 to 196) ensures that a dialog box appears that asks the user if they want to confirm deletion of the asset selected or cancel the action which, if confirmed, removes the record from the database and informs the user that deletion was successful. If the user logged in is marked as a regular user within the database, however, then a flashed message appears informing the user that they do not have permission to delete assets


@main.route('/assets/<int:asset_id>/delete', methods=['POST'])
@login_required
def delete_asset(asset_id):
    asset = Asset.query.get_or_404(asset_id)

    if current_user.role == 'admin':

app/templates/assets.html
{% extends 'base.html' %}

<!-- Lines 5 to 13 check to see if a flashed message has been generated in the 'delete' route for assets in routes.py that is called if a non-admin user (who are restricted from deleting assets) attempts to delete an asset -->

{% block content %}
<div class="container">
    <h1>Asset Management</h1>
    <hr>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        {{ message }}
    </div>
    {% endfor %}

    <!-- Lines 19 to 44 generate a form for the user to input data and make dropdown selections for creating a new asset, which are then pushed to the database if the validation checks pass upon submission -->

    <h3>Create New Asset</h3>
    <br>
    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.category.label(class="form-label") }}
            {{ form.category(class="form-select form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ form.manufacturer.label(class="form-label") }}
            {{ form.manufacturer(class="form-select form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ form.customer.label(class="form-label") }}
            {{ form.customer(class="form-select form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ form.comments.label(class="form-label") }}
            {{ form.comments(class="form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>

    <hr>

    <!-- Lines 52 to 81 use a Jinja2 'for' loop to populate the assets page with all of the assets found in the database -->

    <h3>Asset List</h3>
    <ul class="list-group">
        {% for asset in assets %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-sm-3">
                    <p><strong>Category:</strong><br> {{ asset.category }}</p>
                </div>
                <br>
                <div class="col-sm-3">
                    <p><strong>Manufacturer:</strong><br> {{ asset.manufacturer.name }}</p>
                </div>
                <div class="col-sm-3">
                    <p><strong>Customer:</strong><br> {{ asset.customer.name }}</p>
                </div>
                <div class="col-sm-3">
                    <p style="word-wrap: break-word;"><strong>Comments:</strong><br> {{ asset.comments }}</p>
                </div>
                <div class="col-sm-3">
                    <div class="btn-group" role="group">
                        <a href="{{ url_for('main.edit_asset', asset_id=asset.id) }}" class="btn btn-primary">
                            Edit
                        </a>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                            data-bs-target="#deleteAssetModal{{ asset.id }}">
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>

    <!-- Lines 86 to 108 use a Jinja2 'for' loop to utilise a Bootstrap modal to generate a pop up dialog box that asks the user to confirm or cancel deletion of an asset after clicking the delete button for that asset -->

    {% for asset in assets %}
    <div class="modal fade" id="deleteAssetModal{{ asset.id }}" tabindex="-1" role="dialog"
        aria-labelledby="deleteAssetModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteAssetModalLabel">Confirm Deletion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this asset?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <form action="{{ url_for('main.delete_asset', asset_id=asset.id) }}" method="post">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
<br>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>

<!-- This page serves as the primary HTML document from which all of the other HTML-based pages extend from for the frontend of the app, by making use of the Jinja2 Python template engine -->

<!-- Lines 10 to 17 utilise a Content Delivery Network to incorporate Bootstrap styling and JavaScript elements for the application -->

<head>
    <title>{% block title %}IT Assets Register{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
</head>

<!-- Lines 27 to 52 utilise the Jinja2 templating engine to check if the user is logged in, and if they are they will see navigation links to the Assets, Customers, Manufacturers and Logout pages. But if they aren't, they will only see links to Register and Login -->

<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">
            <img src="{{ url_for('static', filename='nofusslogo_sml.png') }}" alt="Logo" height="50">
        </a>
        {% if current_user.is_authenticated %}
        <p class="navbar-nav text-light"> Logged in as {{ current_user.username }}</p>
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.assets') }}">Assets</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.customers') }}">Customers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.manufacturers') }}">Manufacturers</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.logout') }}">Logout</a>
            </li>
        </ul>
        {% else %}
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.register') }}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('main.login') }}">Login</a>
            </li>
        </ul>
        {% endif %}
    </nav>

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

app/templates/customers.html
{% extends 'base.html' %}

<!-- Lines 5 to 13 check for any flashed messages generated in the 'delete' route for customers in routes.py, and displays them in the user interface if one is called -->

{% block content %}
<div class="container">
    <h1>Customer Management</h1>
    <hr>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        {{ message }}
    </div>
    {% endfor %}

    <!-- Lines 19 to 29 generate a form for the user to input data for creating a new customer, which are then pushed to the database if the validation checks pass upon submission -->

    <h3>Create New Customer</h3>
    <br>
    <form method="POST">
        {{ customer_form.hidden_tag() }}
        <div class="form-group">
            {{ customer_form.name.label(class="form-label") }}
            {{ customer_form.name(class="form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ customer_form.submit(class="btn btn-primary") }}
        </div>
    </form>

    <hr>

    <!-- Lines 37 to 56 use a Jinja2 'for' loop to populate the customers page with all of the customers found in the database -->

    <h2>Customer List</h2>
    <ul class="list-group">
        {% for customer in customers %}
        <li class="list-group-item">
            <div class="row">
                <div class="col-md-10">
                    <p><strong>Name:</strong><br> {{ customer.name }}</p>
                </div>
                <div class="col-sm-3">
                    <div class="btn-group" role="group">
                        <a href="{{ url_for('main.edit_customer', customer_id=customer.id) }}" class="btn btn-primary">
                            Edit
                        </a>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                            data-bs-target="#deleteCustomerModal{{ customer.id }}">
                            Delete
                        </button>
                    </div>
                </div>
            </div>
        </li>
        {% endfor %}
    </ul>
</div>

<!-- Lines 62 to 84 use a Jinja2 'for' loop to utilise a Bootstrap modal to generate a pop up dialog box that asks the user to confirm or cancel deletion of a customer after clicking the delete button for that customer -->

{% for customer in customers %}
<div class="modal fade" id="deleteCustomerModal{{ customer.id }}" tabindex="-1" role="dialog"
    aria-labelledby="deleteCustomerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteCustomerModalLabel">Confirm Deletion</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this customer?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{{ url_for('main.delete_customer', customer_id=customer.id) }}" method="post">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}
<br>
{% endblock %}

app/templates/edit_asset.html
{% extends 'base.html' %}

<!-- Lines 5 to 13 check for any flashed messages generated in the 'edit' route for assets in routes.py, and displays them in the user interface if one is called -->

{% block content %}
<div class="container">
    <h1>Edit Asset</h1>
    <hr>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %}

    <!-- Lines 17 to 44 generate a form for the user to edit the data and dropdown selections for an existing asset in the database, and any changes are then pushed to that record in the database if the validation checks pass upon submission -->

    <form method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.category.label(class="form-label") }}
            {{ form.category(class="form-select form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ form.manufacturer.label(class="form-label") }}
            {{ form.manufacturer(class="form-select form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ form.customer.label(class="form-label") }}
            {{ form.customer(class="form-select form-control") }}
        </div>
        <br>
        <div class="form-group">
            {{ form.comments.label(class="form-label") }}
            {{ form.comments(class="form-control") }}
        </div>
        <br>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">
                Update Asset
            </button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/edit_customer.html
{% extends 'base.html' %}

<!-- Lines 5 to 13 check for any flashed messages generated in the 'edit' route for customers in routes.py, and displays them in the user interface if one is called -->

{% block content %}
<div class="container">
    <h1>Edit Customer</h1>
    <hr>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %}

    <!-- Lines 17 to 31 generate a form for the user to edit the data and dropdown selections for an existing customer in the database, and any changes are then pushed to that record in the database if the validation checks pass upon submission -->

    <form method="POST">
        {{ customer_form.hidden_tag() }}
        <div class="form-group">
            {{ customer_form.name.label(class="form-label") }}
            {{ customer_form.name(class="form-control") }}
        </div>
        <br>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">
                Update Customer
            </button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/edit_manufacturer.html
{% extends 'base.html' %}

<!-- Lines 5 to 13 check for any flashed messages generated in the 'edit' route for manufacturers in routes.py, and displays them in the user interface if one is called -->

{% block content %}
<div class="container">
    <h1>Edit Manufacturer</h1>
    <hr>
    {% for message in get_flashed_messages() %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %}

    <!-- Lines 17 to 31 generate a form for the user to edit the data and dropdown selections for an existing manufacturer in the database, and any changes are then pushed to that record in the database if the validation checks pass upon submission -->

    <form method="POST">
        {{ manufacturer_form.hidden_tag() }}
        <div class="form-group">
            {{ manufacturer_form.name.label(class="form-label") }}
            {{ manufacturer_form.name(class="form-control") }}
        </div>
        <br>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">
                Update Manufacturer
            </button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

<!-- Lines 5 to 20 add the No Fuss logo and an inventory image, in addition to the name of the app, to the homepage. At the very top of the page is where any flashed messages for informing the user that they have succesfully logged in or out (generated in the login/logout routes in routes.py) are displayed -->

{% block content %}
<div class="container mt-4">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-success">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}
    <img src="{{ url_for('static', filename='nofusslogo.png') }}" alt="Logo" class="logo">
    <hr>
    <h1>No Fuss IT Asset Register - Docker</h1>
    <hr>
    <img src="{{ url_for('static', filename='inventory.jpg') }}" height="400">
</div>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

<!-- Lines 5 to 42 generate a form for the user to login with using their username and password, which will only succeed as long as the validation checks in routes.py are passed upon submisson. If the user enters an incorrect username or password, a flashed message generated in the login route in routes.py will be displayed at the top of the page informing the user that they have entered incorrect details. If successful, the user will be redirected to the homepage (index.html) and informed that their login was successful -->

{% block content %}
<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1>Login</h1>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        {% if category == 'danger' %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
        {% elif category == 'success' %}
        <div class="alert alert-success">
            {{ message }}
        </div>
        {% endif %}
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
            </div>
            <br>
            <div class="form-group">
                {{ form.password.label }}
                {{ form.password(class="form-control") }}
            </div>
            <br>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/logout.html
{% extends 'base.html' %}

<!-- Lines 5 to 17 utilise a Bootstrap modal to create a pop up dialog box that asks the user to confirm or cancel the action of logging out of their account -->

{% block content %}
<div class="container">
    <h1>Logout</h1>
    <hr>
    <p>Are you sure you want to log out?</p>

    <form method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token }}">
        <button type="submit" class="btn btn-danger">Logout</button>
        <a href="{{ url_for('main.index') }}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

<!-- Lines 5 to 41 generate a form for the user to register with using a username and password, which will only succeed as long as the validation checks in routes.py are passed upon submisson. If the user enters a username that has already been taken, a flashed message generated in the register route in routes.py will be displayed at the top of the page informing the user that they need to choose a different username. If successful, the user will be redirected to the login page and informed that registration was successful -->

{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h1>Register</h1>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label }}
                {{ form.username(class="form-control") }}
            </div>
            <br>
            <div class="form-group">
                {{ form.password.label }}
                {{ form.password(class="form-control") }}
            </div>
            <br>
            <div class="form-group">
                {{ form.confirm_password.label }}
                {{ form.confirm_password(class="form-control") }}
            </div>
            <br>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}